title: Desiree Cele 
description: "Urban Data Analyst| GIS Database Admin."
logo: "https://github.com/Descele/Desiree_Cele/tree/6fc7896c8c73c0fb9766f640be217626e728a80a/assets{:width="200px"}"
linkedin: "https://www.linkedin.com/in/desiree-cele-783a7026"
show_downloads: false
layout: default 
theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme
markdown: kramdown
highlighter: rouge
