title: Desiree Cele 
description: "Urban Data Analyst| GIS Database Admin."
logo: "https://cdn.jsdelivr.net/gh/Descele/portfolio@main/assets/DNC_headshot_IMG_6187.png"
linkedin: "https://www.linkedin.com/in/desiree-cele-783a7026"
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
markdown: kramdown
highlighter: rouge
