title: Desiree Cele
description: Urban Data Analyst | GIS Database Admin.
logo: /assets/Images/DC_headshot.jpg
linkedin: https://www.linkedin.com/in/desiree-cele-783a7026
show_downloads: false
theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme
markdown: kramdown
highlighter: rouge
