https://github.com/Descele/Desiree_Cele/tree/d82100f5437f743d93719d96c0387ab0487dbcba/asset
title: Desiree Cele
description: "Urban Data Analyst | GIS Database Admin."
logo: "https://github.com/Descele/Desiree_Cele/tree/d82100f5437f743d93719d96c0387ab0487dbcba/asset"
linkedin: "https://www.linkedin.com/in/desiree-cele-783a7026"
show_downloads: false
theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme
markdown: kramdown
highlighter: rouge
