layout: default
title: Desiree Cele 
description: "Urban Data Analyst| GIS Database Admin."
logo: "https://cdn.jsdelivr.net/gh/Descele/portfolio@main/assets/DNC_headshot_IMG_6187.png"
linkedin: "https://www.linkedin.com/in/desiree-cele-783a7026"
show_downloads: false
theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme
markdown: kramdown
highlighter: rouge
